/*
 * Nausf_UPUProtection Service
 *
 * AUSF UPU Protection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package upuprotection

import (
	"github.com/nycu-ucr/gonet/http"

	"github.com/nycu-ucr/gin"
)

// SupiUeUpuPost -
func SupiUeUpuPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
